spring.application.name=jms-orders
spring.main.web-application-type=none
spring.artemis.mode=embedded
spring.artemis.embedded.persistent=false
spring.artemis.embedded.queues=OrdersQueue
demo.queue=OrdersQueue
demo.produce=true
